#include "gpio_ini.h"

uint32_t temp = 0;
uint32_t temp2 = 0;

/********** SET AF FOR ANY GPIO PIN **********/
void Setting_GPIO_AF(GPIO_TypeDef* GPIOx, uint8_t GPIO_PinSource, uint8_t GPIO_AF)
{
	temp = ((uint32_t)(GPIO_AF) << ((uint32_t)((uint32_t)GPIO_PinSource & (uint32_t)0x07) * 4)) ;
  GPIOx->AFR[12 >> 0x03] &= ~((uint32_t)0xF << ((uint32_t)((uint32_t)GPIO_PinSource & (uint32_t)0x07) * 4)) ;
  temp2 = GPIOD->AFR[GPIO_PinSource >> 0x03] | temp;
  GPIOx->AFR[GPIO_PinSource >> 0x03] |= temp2;
}

void GPIO_INIT() 
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN|RCC_AHB1ENR_GPIOBEN|RCC_AHB1ENR_GPIOCEN|RCC_AHB1ENR_GPIODEN; // Set clock for GPIOA - GPIOD
	
	/***************************
	 * SETTING PWM OUTPUT PINS *
	 ***************************/
	/******************** Set PA0 Pin (PWM TIM2_CH1) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER0);
	GPIOA->MODER |= GPIO_MODER_MODER0_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_0);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR0);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR0);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0;
	
	/******************** Set PA1 Pin (PWM TIM2_CH2) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER1);
	GPIOA->MODER |= GPIO_MODER_MODER1_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_1);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR1);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR1);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1;
	
	/******************** Set PA2 Pin (PWM TIM2_CH1) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER2);
	GPIOA->MODER |= GPIO_MODER_MODER2_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_2);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR2);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR2);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2;
	
	/******************** Set PA3 Pin (PWM TIM2_CH2) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER3);
	GPIOA->MODER |= GPIO_MODER_MODER3_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_3);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR3);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR3);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3;
	
	/******************** Set PB0 Pin (PWM TIM3_CH1) ********************/
	GPIOB->MODER &= ~(GPIO_MODER_MODER0);
	GPIOB->MODER |= GPIO_MODER_MODER0_1;
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_0);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR0);
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR0);
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0;
	
	/******************** Set PB1 Pin (PWM TIM3_CH2) ********************/
	GPIOB->MODER &= ~(GPIO_MODER_MODER1);
	GPIOB->MODER |= GPIO_MODER_MODER1_1;
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_1);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR1);
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR1);
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1;
	
	/******************** Set PD12 Pin (PWM TIM4_CH1) ********************/
	GPIOD->MODER &= ~(GPIO_MODER_MODER12);
	GPIOD->MODER |= GPIO_MODER_MODER12_1;
	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT_12);
	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPDR12);
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR12);
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12;
	
	/******************** Set PD13 Pin (PWM TIM4_CH2) ********************/
	GPIOD->MODER &= ~(GPIO_MODER_MODER13);
	GPIOD->MODER |= GPIO_MODER_MODER13_1;
	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT_13);
	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPDR13);
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR13);
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13;
	
	/******************** Set PD14 Pin (PWM TIM4_CH3) ********************/
	GPIOD->MODER &= ~(GPIO_MODER_MODER14);
	GPIOD->MODER |= GPIO_MODER_MODER14_1;
	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT_14);
	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPDR14);
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR14);
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14;
	
	/******************** Set PD15 Pin (PWM TIM4_CH4) ********************/
	GPIOD->MODER &= ~(GPIO_MODER_MODER15);
	GPIOD->MODER |= GPIO_MODER_MODER15_1;
	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT_15);
	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPDR15);
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR15);
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15;
	
	/***************************
	 * SETTING PWM OUTPUT PINS *
	 ***************************/
	/******************** Set PA5 Pin SPI1 (SCK) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER5);
	GPIOA->MODER |= GPIO_MODER_MODER5_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_5);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR5);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR5);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5;
	
	/******************** Set PA6 Pin SPI1 (MISO) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER6);
	GPIOA->MODER |= GPIO_MODER_MODER6_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_6);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR6);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR6);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6;
	
	/******************** Set PA7 Pin SPI1 (MOSI) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER7);
	GPIOA->MODER |= GPIO_MODER_MODER7_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_7);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR7);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR7);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7;
	
	/******************** Set PC10 Pin SPI3 (SCK) ********************/
	GPIOC->MODER &= ~(GPIO_MODER_MODER10);
	GPIOC->MODER |= GPIO_MODER_MODER10_1;
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT_10);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR10);
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR10);
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10;
	
	/******************** Set PC11 Pin SPI3 (MISO) ********************/
	GPIOC->MODER &= ~(GPIO_MODER_MODER11);
	GPIOC->MODER |= GPIO_MODER_MODER11_1;
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT_11);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR11);
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR11);
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11;
	
	/******************** Set PC12 Pin SPI3 (MOSI) ********************/
	GPIOC->MODER &= ~(GPIO_MODER_MODER12);
	GPIOC->MODER |= GPIO_MODER_MODER12_1;
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT_12);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR12);
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR12);
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12;
	
	/**********************
	 * SETTING USART PINS *
	 **********************/
	/******************** Set PA9 Pin USART1 (TX) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER9);
	GPIOA->MODER |= GPIO_MODER_MODER9_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_9);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR9);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR9);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9;
	
	/******************** Set PA10 Pin USART1 (RX) ********************/
	GPIOA->MODER &= ~(GPIO_MODER_MODER10);
	GPIOA->MODER |= GPIO_MODER_MODER10_1;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_10);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR10);
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR10);
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10;
	
	/******************** Set PB10 Pin USART3 (TX) ********************/
	GPIOB->MODER &= ~(GPIO_MODER_MODER10);
	GPIOB->MODER |= GPIO_MODER_MODER10_1;
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_10);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR10);
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR10);
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10;
	
	/******************** Set PB11 Pin USART3 (RX) ********************/
	GPIOB->MODER &= ~(GPIO_MODER_MODER11);
	GPIOB->MODER |= GPIO_MODER_MODER11_1;
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_11);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR11);
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR11);
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11;
	
	/******************** Set PC6 Pin USART6 (TX) ********************/
	GPIOC->MODER &= ~(GPIO_MODER_MODER6);
	GPIOC->MODER |= GPIO_MODER_MODER6_1;
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT_6);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR6);
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR6_0;
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR6);
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6;
	
	/******************** Set PC7 Pin USART6 (RX) ********************/
	GPIOC->MODER &= ~(GPIO_MODER_MODER7);
	GPIOC->MODER |= GPIO_MODER_MODER7_1;
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT_7);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR7);
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR7);
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7;
	
	/****************************************
	 * SETTING ALTERNATE FUNCTIONS FOR PINS *
	 ****************************************/
	/******************** Set AF for PWM Pins ********************/
	Setting_GPIO_AF(GPIOA, GPIO_PinSource0, GPIO_AF_TIM2);
	Setting_GPIO_AF(GPIOA, GPIO_PinSource1, GPIO_AF_TIM2);
	Setting_GPIO_AF(GPIOA, GPIO_PinSource2, GPIO_AF_TIM2);
	Setting_GPIO_AF(GPIOA, GPIO_PinSource3, GPIO_AF_TIM2);
	Setting_GPIO_AF(GPIOB, GPIO_PinSource0, GPIO_AF_TIM3);
	Setting_GPIO_AF(GPIOB, GPIO_PinSource1, GPIO_AF_TIM3);
	Setting_GPIO_AF(GPIOD, GPIO_PinSource12, GPIO_AF_TIM4);
	Setting_GPIO_AF(GPIOD, GPIO_PinSource13, GPIO_AF_TIM4);
	Setting_GPIO_AF(GPIOD, GPIO_PinSource14, GPIO_AF_TIM4);
	Setting_GPIO_AF(GPIOD, GPIO_PinSource15, GPIO_AF_TIM4);
	
	/******************** Set AF for PA9-10 Pins (USART1) ********************
	// Those Pins are wrong!!! 
	// If set AF for those pins, microcontroller is closed to connecting!!!
	// MESSAGE: No target connected!
	// USART is wrong on PA9-10!
	Setting_GPIO_AF(GPIOA, GPIO_PinSource9, GPIO_AF_USART1);
	Setting_GPIO_AF(GPIOA, GPIO_PinSource10, GPIO_AF_USART1);*/
	
	/******************** Set AF for PB10-11 Pins (USART3) ********************/
	Setting_GPIO_AF(GPIOB, GPIO_PinSource10, GPIO_AF_USART3);
	Setting_GPIO_AF(GPIOB, GPIO_PinSource11, GPIO_AF_USART3);
	
	/******************** Set AF for PC6-7 Pins (USART6) ********************/
	Setting_GPIO_AF(GPIOC, GPIO_PinSource6, GPIO_AF_USART6);
	Setting_GPIO_AF(GPIOC, GPIO_PinSource7, GPIO_AF_USART6);
}

